import net from 'node:net';
import {getDb} from './db';
import {decryptText} from './secure';

export const SMS_DEFAULTS={
  sms_prefix:'[한빛상품권]',
  sms_admin_phone:'',
  sms_received_customer_enabled:'1',
  sms_received_admin_enabled:'1',
  sms_reviewing_enabled:'1',
  sms_paid_enabled:'1',
  sms_rejected_enabled:'1',
  sms_template_received_customer:'상품권 판매 신청이 정상 접수되었습니다. 확인후 5분이내 입금이 완료됩니다.',
  sms_template_received_admin:'신규신청 {접수번호} / {신청자} / {전화번호} / {신청금액}',
  sms_template_reviewing:'{접수번호} 상품권 PIN을 확인하고 있습니다.',
  sms_template_paid:'{접수번호} 상품권 판매금액 {입금금액} 입금이 완료되었습니다.',
  sms_template_rejected:'{접수번호} 상품권 신청이 처리 불가 상태입니다.'
};

export async function ensureSmsSchema(){const sql=getDb();await sql`CREATE TABLE IF NOT EXISTS sms_logs(id BIGSERIAL PRIMARY KEY,order_id BIGINT NULL,recipient_type VARCHAR(20) NOT NULL DEFAULT 'customer',recipient_phone_last4 VARCHAR(4) NOT NULL DEFAULT '',event_type VARCHAR(40) NOT NULL,message_content TEXT NOT NULL,provider VARCHAR(20) NOT NULL DEFAULT 'icode',send_status VARCHAR(20) NOT NULL,result_code VARCHAR(10) NOT NULL DEFAULT '',provider_response TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;for(const [k,v] of Object.entries(SMS_DEFAULTS)){await sql`INSERT INTO service_settings(setting_key,setting_value) VALUES(${k},${v}) ON CONFLICT(setting_key) DO NOTHING`}}
export async function getSmsSettings(){await ensureSmsSchema();const sql=getDb();const keys=Object.keys(SMS_DEFAULTS);const rows=await sql`SELECT setting_key,setting_value FROM service_settings WHERE setting_key=ANY(${keys})`;return {...SMS_DEFAULTS,...Object.fromEntries(rows.map(r=>[r.setting_key,String(r.setting_value??'')]))}}
export function normalizePhone(v){return String(v||'').replace(/\D/g,'')}
export function renderSmsTemplate(t,vars){let text=String(t||'');for(const [k,v] of Object.entries(vars||{}))text=text.split(`{${k}}`).join(String(v??''));return text.trim()}
function withPrefix(m,p){const text=String(m||'').trim().replace(/^\[[^\]\r\n]{1,40}\]\s*/u,'');return p?`${p} ${text}`.trim():text}
function buildPacket({key,tel,cb,msg,title=''}){const payload={key,tel,cb,msg:String(msg).slice(0,2000),title,date:'',charset:'utf-8'};const json=JSON.stringify(payload);return `06${String(Buffer.byteLength(json,'utf8')).padStart(4,'0')}${json}`}
export async function sendIcodeSms(phone,message,{title='한빛 상품권'}={}){const token=String(process.env.ICODE_TOKEN_KEY||'').trim();const callback=normalizePhone(process.env.ICODE_CALLBACK_PHONE||'');const tel=normalizePhone(phone);if(!token)throw new Error('ICODE_TOKEN_KEY가 설정되지 않았습니다.');if(!/^01[016789]\d{7,8}$/.test(tel))throw new Error('수신 휴대전화 번호가 올바르지 않습니다.');if(!/^\d{9,12}$/.test(callback))throw new Error('ICODE_CALLBACK_PHONE 발신번호를 확인해 주세요.');const packet=buildPacket({key:token,tel,cb:callback,msg:message,title});const host=process.env.ICODE_HOST||'211.172.232.124';const port=Number(process.env.ICODE_PORT||9201);return new Promise((resolve,reject)=>{const socket=net.createConnection({host,port});let response='';const timer=setTimeout(()=>{socket.destroy();reject(new Error('아이코드 서버 응답 시간이 초과되었습니다.'));},8000);socket.setEncoding('utf8');socket.on('connect',()=>socket.write(packet));socket.on('data',chunk=>{response+=chunk;if(response.length>=8){clearTimeout(timer);socket.end();const code=response.slice(6,8);resolve({success:code==='00',pending:code==='17',code,response})}});socket.on('error',e=>{clearTimeout(timer);reject(e)});socket.on('end',()=>{if(!response){clearTimeout(timer);reject(new Error('아이코드 서버에서 결과를 받지 못했습니다.'))}})})}
export async function logSms({orderId=null,recipientType='customer',phone,eventType,message,status,resultCode='',response=''}){await ensureSmsSchema();const sql=getDb();const tel=normalizePhone(phone);await sql`INSERT INTO sms_logs(order_id,recipient_type,recipient_phone_last4,event_type,message_content,provider,send_status,result_code,provider_response) VALUES(${orderId},${recipientType},${tel.slice(-4)},${eventType},${message},'icode',${status},${resultCode},${String(response||'').slice(0,1000)})`}
export async function sendAndLogSms(args){const s=await getSmsSettings();const message=withPrefix(args.message,s.sms_prefix);try{const r=await sendIcodeSms(args.phone,message);const status=r.success?'sent':r.pending?'pending':'failed';await logSms({...args,message,status,resultCode:r.code,response:r.response});return {...r,status}}catch(e){await logSms({...args,message,status:'failed',response:e?.message||String(e)});throw e}}
export async function sendNewOrderSms({orderId,orderNo,customerName,phone,requestedAmount,expectedAmount}){const s=await getSmsSettings();const tel=normalizePhone(phone);const vars={접수번호:orderNo,신청자:customerName,전화번호:tel,신청금액:`${Number(requestedAmount||0).toLocaleString()}원`,입금금액:`${Number(expectedAmount||0).toLocaleString()}원`};const out=[];if(s.sms_received_customer_enabled==='1'){try{out.push(await sendAndLogSms({orderId,recipientType:'customer',phone:tel,eventType:'received_customer',message:renderSmsTemplate(s.sms_template_received_customer,vars)}))}catch(e){console.error('customer sms failed',e)}}if(s.sms_received_admin_enabled==='1'&&normalizePhone(s.sms_admin_phone)){try{out.push(await sendAndLogSms({orderId,recipientType:'admin',phone:s.sms_admin_phone,eventType:'received_admin',message:renderSmsTemplate(s.sms_template_received_admin,vars)}))}catch(e){console.error('admin sms failed',e)}}return out}
export async function sendOrderEventSms(orderId,eventType){const s=await getSmsSettings();const sql=getDb();const rows=await sql`SELECT id,order_no,customer_name,phone_encrypted,requested_amount,expected_amount FROM orders WHERE id=${Number(orderId)} AND deleted_at IS NULL LIMIT 1`;if(!rows.length)return[];const o=rows[0],phone=decryptText(o.phone_encrypted);const vars={접수번호:o.order_no,신청자:o.customer_name,전화번호:phone,신청금액:`${Number(o.requested_amount||0).toLocaleString()}원`,입금금액:`${Number(o.expected_amount||0).toLocaleString()}원`};let template='',enabled='0',type='';if(eventType==='reviewing'){template=s.sms_template_reviewing;enabled=s.sms_reviewing_enabled;type='status_reviewing'}if(eventType==='paid'){template=s.sms_template_paid;enabled=s.sms_paid_enabled;type='status_paid'}if(eventType==='rejected'){template=s.sms_template_rejected;enabled=s.sms_rejected_enabled;type='status_rejected'}if(enabled!=='1'||!template)return[];try{return [await sendAndLogSms({orderId:Number(orderId),recipientType:'customer',phone,eventType:type,message:renderSmsTemplate(template,vars)})]}catch(e){console.error('status sms failed',e);return[]}}
